<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>7510d67b-338e-45e5-a7cf-4ae073417d83</elementGuidId>
    <imagePath></imagePath>
    <name>main_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/section[1]/main[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="bdl-checkout-layout__main"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>