<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>9f1c8c13-15f5-4e82-88d1-8f5f8462b0c6</elementGuidId>
    <imagePath></imagePath>
    <name>button_continue_to_payment</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/section[1]/main[1]/div[1]/div[2]/div[1]/form[1]/div[3]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="MuiButtonBase-root\ MuiButton-root\ MuiButton-contained\ MuiButton-containedPrimary\ MuiButton-sizeMedium\ MuiButton-containedSizeMedium\ MuiButton-root\ MuiButton-contained\ MuiButton-containedPrimary\ MuiButton-sizeMedium\ MuiButton-containedSizeMedium\ css-1hw9j7s"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'submit') and equals(@text,'CONTINUE TO PAYMENT')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>CONTINUE TO PAYMENT</value>
        <webElementGuid>e21358b0-6f06-4451-85fc-169429a6678c</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>submit</value>
        <webElementGuid>e21358b0-6f06-4451-85fc-169429a6678c</webElementGuid>
    </webElementProperties>
</WebElementEntity>